global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api'
    scrape_interval: 5s
    static_configs:
      - targets: ['backend:8000', 'mediassist-backend-service:8000']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

rule_files:
  - "/etc/prometheus/alert.rules.yml"